server:
  port:8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    platform: postgres
    username: postgres
    password: kim12345

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
